# Generated by Django 6.0.4 on 2026-04-20 00:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedAnalysisLayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('layout', models.TextField()),
                ('context', models.CharField(default='global', max_length=64)),
                ('is_default', models.BooleanField(db_column='isDefault', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'SavedAnalysisLayout',
                'managed': True,
            },
        ),
    ]
