# Generated by Django 6.0.4 on 2026-04-20 00:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lap_number', models.IntegerField(db_column='lap_number')),
                ('lap_time', models.FloatField(blank=True, db_column='lap_time', null=True)),
                ('analyzed', models.BooleanField(default=False)),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('driver_comments', models.TextField(blank=True, db_column='driver_comments', null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('plot_configs', models.TextField(blank=True, db_column='plot_configs', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='laps', to='events.session')),
            ],
            options={
                'db_table': 'laps',
                'managed': True,
                'unique_together': {('session', 'lap_number')},
            },
        ),
        # Add database-level defaults for RisingWave JDBC sink compatibility
        migrations.RunSQL(
            sql="""
                ALTER TABLE laps ALTER COLUMN id SET DEFAULT gen_random_uuid();
                ALTER TABLE laps ALTER COLUMN analyzed SET DEFAULT false;
                ALTER TABLE laps ALTER COLUMN "createdAt" SET DEFAULT NOW();
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
                ('lap', models.ForeignKey(db_column='lapId', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='telemetry.lap')),
            ],
            options={
                'db_table': 'ChatMessage',
                'managed': True,
            },
        ),
    ]
