# Generated by Django 6.0.4 on 2026-04-20 00:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField(blank=True, db_column='startDate', null=True)),
                ('end_date', models.DateTimeField(blank=True, db_column='endDate', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Event',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RunPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('event', models.ForeignKey(blank=True, db_column='eventId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_plans', to='events.event')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='run_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'RunPlan',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=32)),
                ('status', models.CharField(default='active', max_length=32)),
                ('started', models.BooleanField(default=False)),
                ('read_access', models.CharField(db_column='readAccess', default='PRIVATE', max_length=32)),
                ('read_access_org_id', models.CharField(blank=True, db_column='readAccessOrgId', max_length=255, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('plot_configs', models.TextField(blank=True, db_column='plotConfigs', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('event', models.ForeignKey(db_column='eventId', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='events.event')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, db_column='vehicleId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='vehicles.vehicle')),
                ('vehicle_configuration', models.ForeignKey(blank=True, db_column='vehicleConfigurationId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='vehicles.vehicleconfiguration')),
                ('vehicle_setup', models.ForeignKey(blank=True, db_column='vehicleSetupId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='vehicles.vehiclesetup')),
            ],
            options={
                'db_table': 'Session',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RunPlanItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('session_name', models.CharField(db_column='sessionName', max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='planned', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('run_plan', models.ForeignKey(db_column='runPlanId', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='events.runplan')),
                ('vehicle', models.ForeignKey(blank=True, db_column='vehicleId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_plan_items', to='vehicles.vehicle')),
                ('vehicle_configuration', models.ForeignKey(blank=True, db_column='vehicleConfigurationId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_plan_items', to='vehicles.vehicleconfiguration')),
                ('vehicle_setup', models.ForeignKey(blank=True, db_column='vehicleSetupId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_plan_items', to='vehicles.vehiclesetup')),
                ('session', models.OneToOneField(blank=True, db_column='sessionId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_plan_item', to='events.session')),
            ],
            options={
                'db_table': 'RunPlanItem',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_at'], name='Event_created_cd9a9d_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user'], name='Event_userId_b48e9e_idx'),
        ),
    ]
