-- RisingWave: Postgres sink for completed laps
--
-- Writes one row per completed lap into the app metadata Postgres DB.
-- Uses upsert keyed by (session_id, lap_number).

-- Drop existing sink and MV for idempotent re-init
DROP SINK IF EXISTS laps_postgres_upsert;
DROP MATERIALIZED VIEW IF EXISTS completed_laps;

-- ── Laps (one row per lap, updated with max elapsed time) ─────────────
-- Use MAX(lap_time) GROUP BY (session_id, lap_number).
-- Each lap's telemetry has lap_time resetting to 0 at the start, so
-- MAX(lap_time) for each partition gives the correct elapsed duration.
-- This is stable under the 30-second watermark GC: the LAG(lap_time)
-- approach caused all laps to show the same time because, after GC
-- purged older frames, the LAG was recomputed incorrectly and the
-- upsert trigger overwrote the correct values.
CREATE MATERIALIZED VIEW completed_laps AS
SELECT
    session_id,
    lap_number,
    MAX(lap_time) / 1000.0 AS lap_time
FROM telemetry_samples
WHERE lap_number > 0
GROUP BY session_id, lap_number;

-- ── Sink: Postgres append-only insert into laps table ────────────────
-- Requires the laps table to have columns:
--   session_id (uuid), lap_number (int), lap_time (float)
-- The laps table PK is a UUID generated by Postgres (not session_id,lap_number),
-- so upsert mode cannot be used here (RisingWave requires PK match for upsert).
-- Instead we use append-only and rely on the Postgres trigger
-- fn_laps_upsert_on_conflict (in infra/postgres/migrations/003_laps_upsert_trigger.sql)
-- to convert duplicate inserts into UPDATE SET lap_time = ... on (session_id, lap_number).
CREATE SINK laps_postgres_upsert
FROM completed_laps
WITH (
  connector = 'jdbc',
  jdbc.url = 'jdbc:postgresql://postgres:5432/purplesector',
  user = 'purplesector',
  password = 'devpassword',
  table.name = 'laps',
  type = 'append-only',
  force_append_only = 'true'
);
