# Generated by Django 6.0.4 on 2026-04-20 00:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('in_service_date', models.DateTimeField(blank=True, db_column='inServiceDate', null=True)),
                ('out_of_service_date', models.DateTimeField(blank=True, db_column='outOfServiceDate', null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Vehicle',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VehicleConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('parts', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_configurations', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(db_column='vehicleId', on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'VehicleConfiguration',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VehicleSetup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('parameters', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_setups', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(db_column='vehicleId', on_delete=django.db.models.deletion.CASCADE, related_name='setups', to='vehicles.vehicle')),
                ('vehicle_configuration', models.ForeignKey(blank=True, db_column='vehicleConfigurationId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setups', to='vehicles.vehicleconfiguration')),
            ],
            options={
                'db_table': 'VehicleSetup',
                'managed': True,
            },
        ),
    ]
